In [10]:
# Read the downloaded CSV file
import pandas as pd
df = pd.read_csv(r"C:\Users\zholl\Downloads\.kaggle\covid19_global_statistics_2026.csv")
#df.head(25)

In [85]:
df.head(5)

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests,active_case_rate,case_fatality_rate,cases_per_100k,deaths_per_100k
0,Africa,Eritrea,3662244,2026-02-16,NaN,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0,0.000000,0.010109,278.217399,2.812483
1,Africa,Niger,26083660,2026-02-16,NaN,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0,0.073407,0.031417,38.073645,1.196151
2,Africa,Saint-Helena,6115,2026-02-16,NaN,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,0.999077,NaN,35421.095666,NaN
3,South-America,Falkland-Islands,3539,2026-02-16,NaN,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,0.000000,NaN,54535.179429,NaN
4,North-America,Montserrat,4965,2026-02-16,NaN,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,0.013542,0.005702,28257.804632,161.127895

In [51]:
#Create new columns based on information you already have

active case rate
df['active_case_rate']=df['active_cases']/df['total_cases']

case fatlity rate
df['case_fatality_rate']=df['total_deaths']/df['total_cases']

cases per 100k people
df["cases_per_100k"] = (df["total_cases"] / df["population"]) * 100000

deaths per 100k people
df["deaths_per_100k"] = (df["total_deaths"] / df["population"]) * 100000

case growth rate
df["case_growth_rate"] = df["new_cases"] / df["total_cases"]
df = df.drop(columns = ["case_growth_rate"])

#How many continents are in this dataset? What are the continents?
df['continent'].unique()
df['continent'].nunique()

In [62]:
#convert the date column data type (object) to a datetime data type
#df.dtypes
df['date'] = pd.to_datetime(df['date'],format='%Y-%m-%d')

In [76]:
df.dtypes

continent                     object
country                       object
population                     int64
date                  datetime64[ns]
new_cases                    float64
active_cases                 float64
cases_per_million            float64
total_cases                    int64
new_deaths                   float64
deaths_per_million           float64
total_deaths                 float64
tests_per_million            float64
total_tests                  float64
active_case_rate             float64
case_fatality_rate           float64
cases_per_100k               float64
deaths_per_100k              float64
dtype: object

In [73]:
#convert the population data type to integer
#We do not want to see scientific notation for large numbers

#df["population"] = df["population"].fillna(0).astype("int64")

In [75]:
df.head(20)

,continent,country,population,date,new_cases,active_cases,cases_per_million,total_cases,new_deaths,deaths_per_million,total_deaths,tests_per_million,total_tests,active_case_rate,case_fatality_rate,cases_per_100k,deaths_per_100k
0,Africa,Eritrea,3662244,2026-02-16,NaN,0.0,2782.0,10189,NaN,28.0,103.0,6470.0,23693.0,0.000000,0.010109,278.217399,2.812483
1,Africa,Niger,26083660,2026-02-16,NaN,729.0,381.0,9931,NaN,12.0,312.0,9759.0,254538.0,0.073407,0.031417,38.073645,1.196151
2,Africa,Saint-Helena,6115,2026-02-16,NaN,2164.0,354211.0,2166,NaN,NaN,NaN,NaN,NaN,0.999077,NaN,35421.095666,NaN
3,South-America,Falkland-Islands,3539,2026-02-16,NaN,0.0,545352.0,1930,NaN,NaN,NaN,2439107.0,8632.0,0.000000,NaN,54535.179429,NaN
4,North-America,Montserrat,4965,2026-02-16,NaN,19.0,282578.0,1403,NaN,1611.0,8.0,3577442.0,17762.0,0.013542,0.005702,28257.804632,161.127895
5,NaN,Diamond-Princess,0,2026-02-16,NaN,0.0,NaN,712,NaN,NaN,13.0,NaN,NaN,0.000000,0.018258,NaN,NaN
6,Europe,Vatican-City,799,2026-02-16,NaN,0.0,36295.0,29,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,3629.536921,NaN
7,Africa,Western-Sahara,626161,2026-02-16,NaN,0.0,16.0,10,NaN,2.0,1.0,NaN,NaN,0.000000,0.100000,1.597033,0.159703
8,NaN,MS-Zaandam,0,2026-02-16,NaN,0.0,NaN,9,NaN,NaN,2.0,NaN,NaN,0.000000,0.222222,NaN,NaN
9,Asia,China,1448471400,2026-02-16,NaN,118977.0,347.0,503302,NaN,4.0,5272.0,110461.0,160000000.0,0.236393,0.010475,34.747113,0.363970
10,Africa,Liberia,5305117,2026-02-16,NaN,12.0,1525.0,8090,NaN,56.0,295.0,26356.0,139824.0,0.001483,0.036465,152.494281,5.560669
11,Oceania,Nauru,10903,2026-02-16,NaN,45.0,494635.0,5393,NaN,92.0,1.0,1881042.0,20509.0,0.008344,0.000185,49463.450426,9.171788
12,North-America,Caribbean-Netherlands,26647,2026-02-16,3.0,1168.0,438398.0,11682,NaN,1426.0,38.0,1130559.0,30126.0,0.099983,0.003253,43839.831876,142.605171
13,Africa,Comoros,907419,2026-02-16,NaN,9.0,10038.0,9109,NaN,177.0,161.0,NaN,NaN,0.000988,0.017675,1003.836155,17.742630
14,Africa,Guinea-Bissau,2063367,2026-02-16,NaN,508.0,4659.0,9614,NaN,86.0,177.0,70385.0,145231.0,0.052840,0.018411,465.937470,8.578212
15,Africa,Chad,17413580,2026-02-16,NaN,2633.0,442.0,7701,NaN,11.0,194.0,10988.0,191341.0,0.341904,0.025192,44.224106,1.114073
16,North-America,Sint-Maarten,43966,2026-02-16,NaN,54.0,251353.0,11051,NaN,2093.0,92.0,1411454.0,62056.0,0.004886,0.008325,25135.331847,209.252604
17,Oceania,Wallis-and-Futuna,10982,2026-02-16,NaN,3104.0,323256.0,3550,NaN,728.0,8.0,1867419.0,20508.0,0.874366,0.002254,32325.623748,72.846476
18,North-America,St-Barth,9945,2026-02-16,NaN,NaN,553746.0,5507,NaN,603.0,6.0,7908095.0,78646.0,NaN,0.001090,55374.560080,60.331825
19,North-America,Saint-Kitts-and-Nevis,53871,2026-02-16,NaN,0.0,122645.0,6607,NaN,891.0,48.0,2356704.0,126958.0,0.000000,0.007265,12264.483674,89.101743

In [77]:
#load into SQL
#import sqlalchemy as sal
#engine = sal.create_engine('mssql://localhost/master?driver=')
#conn = engine.connect()

import urllib
import sqlalchemy as sal
from sqlalchemy import create_engine

params = urllib.parse.quote_plus(
    "Driver={ODBC Driver 17 for SQL Server};"
    "Server=localhost;"
    "Database=CovidDB;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

engine = sal.create_engine(f"mssql+pyodbc:///?odbc_connect={params}")

In [78]:
conn = engine.connect()
df.to_sql('Covid_nums',con=conn,index=False,if_exists='replace')

C:\Users\zholl\AppData\Local\Temp\ipykernel_13788\1863142324.py:1: SAWarning: Unrecognized server version info '17.0.1000.7'.  Some SQL Server features may not function properly.
  conn = engine.connect()

115

In [82]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)', 'ODBC Driver 18 for SQL Server']